### ISSUE TITLE
 WARN...java.io.IOException: Connection reset by peer

### ISSUE THREAD

**Issue by mobilesoftsmith** [christophery/pushy#87]
Hi,

First of all, thanks for your great work.

I have a push server running as a service on Linux. I find this warning showing up after running 1 or 2 hours. The notification can still be sent out. It is just annoying. 

[nioEventLoopGroup-4-1] WARN com.relayrides.pushy.apns.ApnsClientHandler - APNs client pipeline caught an exception.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1054)
	at io.netty.buffer.WrappedByteBuf.writeBytes(WrappedByteBuf.java:783)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:245)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:106)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:527)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:484)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:398)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:370)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)

And separately, this message appears frequently also:

[nioEventLoopGroup-8-1] INFO com.relayrides.pushy.apns.ApnsClient - Connection to api.development.push.apple.com/17.172.238.203:443 restored.
 
Is this normal?

**Comment by christophery** [comment]
I think you have the wrong Github repo, this one is for an off-canvas menu not a push server.

**Comment by mobilesoftsmith** [comment]
I am sorry.
